module.exports = {
    error(msg, command) {
        console.log(`[ERR] in ${command} command, executed by ${msg.author.tag} at ${msg.createdAt}`);
    },
    action(msg, command) {
        console.log(`[CMD] ${command} executed by ${msg.author.tag} at ${msg.createdAt}`);
    },
    notice(msg, details) {
        console.log(`[INFO] ${details}, generated by command from ${msg.author.tag} at ${msg.createdAt}`);
    },
    misc(details) {
        console.log(`[MISC] ${details}`);
    }
}